#!/bin/bash

# trconnects CLI - Quick Reference Card
# Place this in your terminal or save as a reference

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║         🚀 trconnects CLI - Quick Reference                        ║"
echo "║    Unified AI Platform: Ollama + Claude + Qwen + LLM              ║"
echo "╚════════════════════════════════════════════════════════════════════╝"

echo ""
echo "📍 LOCATION:"
echo "   cd ~/Downloads/content\ \(1\)/trconnects"
echo ""

echo "🎯 START HERE:"
echo ""
echo "1. Check status:"
echo "   node bin/trconnects status"
echo ""
echo "2. Install fast model:"
echo "   node bin/trconnects pull neural-chat:latest"
echo ""
echo "3. Start chatting:"
echo "   node bin/trconnects chat"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💬 CHAT COMMANDS:"
echo "   node bin/trconnects chat                          (with default model)"
echo "   node bin/trconnects chat --name qwen3.5:latest    (with specific model)"
echo "   node bin/trconnects chat --model claude            (with Claude API)"
echo ""

echo "🎨 CODE GENERATION:"
echo "   node bin/trconnects gen \"description\" --type react        → React JSX"
echo "   node bin/trconnects gen \"description\" --type api          → Node/Python API"
echo "   node bin/trconnects gen \"description\" --type mobile       → React Native"
echo "   node bin/trconnects gen \"description\" --type db           → SQL"
echo "   node bin/trconnects gen \"description\" --type python       → Python"
echo ""
echo "   Save to file:"
echo "   node bin/trconnects gen \"description\" --type react -o App.jsx"
echo ""

echo "📦 MODEL MANAGEMENT:"
echo "   node bin/trconnects list                 (show all models)"
echo "   node bin/trconnects pull neural-chat     (install model)"
echo "   node bin/trconnects status               (check connections)"
echo ""

echo "⚙️  CONFIGURATION:"
echo "   node bin/trconnects config --list                 (view settings)"
echo "   node bin/trconnects config --get ollama.host     (get value)"
echo "   node bin/trconnects config --set key=value       (set value)"
echo ""

echo "📚 HELP & INFO:"
echo "   node bin/trconnects --help               (all commands)"
echo "   node bin/trconnects help chat             (command-specific help)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 EXAMPLE WORKFLOWS:"
echo ""
echo "React App:"
echo "   node bin/trconnects gen 'todo list with add/remove' --type react -o TodoList.jsx"
echo ""
echo "Python Backend:"
echo "   node bin/trconnects gen 'user management API' --type api -o api.py"
echo ""
echo "Mobile Login:"
echo "   node bin/trconnects gen 'authentication screen' --type mobile -o Login.jsx"
echo ""
echo "Database:"
echo "   node bin/trconnects gen 'ecommerce schema' --type db -o schema.sql"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🌐 WEB UI:"
echo "   Web Panel: http://localhost:3000"
echo "   Start UI:  cd web-ui && npm run server"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 RECOMMENDED MODELS:"
echo "   Fast:     neural-chat:latest (4.1 GB)"
echo "   Small:    qwen2.5:latest (1.5 GB)" 
echo "   Code:     qwen2.5-coder:latest (best for coding)"
echo "   Advanced: deepseek-coder-v2:latest (complex tasks)"
echo ""
echo "   Install:  node bin/trconnects pull [model-name]"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 SETUP CLAUDE (Optional):"
echo ""
echo "1. Get API key from: https://console.anthropic.com"
echo ""
echo "2. Add to .env file in trconnects directory:"
echo "   echo \"CLAUDE_API_KEY=sk-ant-your-key-here\" > .env"
echo ""
echo "3. Use Claude:"
echo "   node bin/trconnects chat --model claude --name claude-3-opus"
echo "   node bin/trconnects gen \"description\" --model claude"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ STATUS:"
echo "   Ollama:     ✓ Connected"
echo "   Web UI:     ✓ Running at http://localhost:3000"
echo "   Claude:     ⚠  Optional (add API key to enable)"
echo "   CLI:        ✓ Ready to use"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 Full Documentation:"
echo "   README.md             - Complete guide"
echo "   QUICK_START.md        - Getting started"
echo "   TRCONNECTS_GUIDE.md   - Integration details"
echo ""
echo "Happy Coding! 🚀"
echo ""
